### ISSUE TITLE
Hosted version results in 404

### ISSUE THREAD

**Issue by The-Compiler** [kmichel-sereema/python-importtime-graph#1]
Hey, thanks for this tool - it looks immensely useful to find out how to make [my project](https://www.qutebrowser.org/) start faster!

While it's easy to download `index.html` and run it locally, it looks like this was hosted at https://kmichel-sereema.github.io/python-importtime-graph/ (according to the readme), however, this leads to a 404.

It looks like https://kmichel.github.io/python-importtime-graph/ works (I suppose you changed your username at some point?) - I would open a PR to update the readme, but the URL in the repository settings is outdated as well.

**Comment by kmichel** [comment]
Hi,

Thank you for the info, I did change the owner the project
and forgot to update the link.

I've updated the link in the readme, however I haven't found the
URL in the repository settings you're mentioning. Maybe it's only an
outdated URL in a local copy you pulled before the rename ?

If that's the case, maybe you need to [change the upstream](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/configuring-a-remote-for-a-fork)
to track the new remote URL.

**Comment by The-Compiler** [comment]
Sorry for being a bit vague - I mean this:

![image](https://user-images.githubusercontent.com/625793/108521834-6e0a5d80-72cc-11eb-9932-463fb50b7f75.png)

You should use a gear icon there, which you can use to edit the URL.

**Comment by kmichel** [comment]
Oh yeah, this one :facepalm: 

It's fixed, thank you :)
